services:
  db:
    image: postgres:18-alpine
    container_name: policy-forum-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: policy_forum
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
