// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comments.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createComments = `-- name: CreateComments :one
INSERT INTO comments (id, post_id, user_id, parent_id,content, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, post_id, user_id, content, created_at, updated_at, parent_id, score
`

type CreateCommentsParams struct {
	ID        uuid.UUID   `json:"id"`
	PostID    uuid.UUID   `json:"post_id"`
	UserID    uuid.UUID   `json:"user_id"`
	ParentID  pgtype.UUID `json:"parent_id"`
	Content   string      `json:"content"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}

func (q *Queries) CreateComments(ctx context.Context, arg CreateCommentsParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComments,
		arg.ID,
		arg.PostID,
		arg.UserID,
		arg.ParentID,
		arg.Content,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentID,
		&i.Score,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comments
WHERE id = $1 AND user_id = $2
`

type DeleteCommentParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteComment(ctx context.Context, arg DeleteCommentParams) error {
	_, err := q.db.Exec(ctx, deleteComment, arg.ID, arg.UserID)
	return err
}

const listCommentsByNewest = `-- name: ListCommentsByNewest :many
SELECT comments.id, comments.parent_id, comments.content, comments.created_at, comments.updated_at, users.id AS author_id, users.name AS author_name,
    (SELECT COUNT(*) FROM comments AS replies WHERE replies.parent_id = comments.id) AS reply_count
FROM comments
JOIN users ON comments.user_id = users.id
WHERE comments.post_id = $1
AND(
($3::uuid IS NULL AND comments.parent_id IS NULL)
OR
(comments.parent_id = $3)
)
AND ($4::timestamp IS NULL OR comments.created_at < $4)
ORDER BY comments.created_at DESC
LIMIT $2
`

type ListCommentsByNewestParams struct {
	PostID   uuid.UUID        `json:"post_id"`
	Limit    int32            `json:"limit"`
	ParentID pgtype.UUID      `json:"parent_id"`
	Cursor   pgtype.Timestamp `json:"cursor"`
}

type ListCommentsByNewestRow struct {
	ID         uuid.UUID   `json:"id"`
	ParentID   pgtype.UUID `json:"parent_id"`
	Content    string      `json:"content"`
	CreatedAt  time.Time   `json:"created_at"`
	UpdatedAt  time.Time   `json:"updated_at"`
	AuthorID   uuid.UUID   `json:"author_id"`
	AuthorName string      `json:"author_name"`
	ReplyCount int64       `json:"reply_count"`
}

func (q *Queries) ListCommentsByNewest(ctx context.Context, arg ListCommentsByNewestParams) ([]ListCommentsByNewestRow, error) {
	rows, err := q.db.Query(ctx, listCommentsByNewest,
		arg.PostID,
		arg.Limit,
		arg.ParentID,
		arg.Cursor,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentsByNewestRow
	for rows.Next() {
		var i ListCommentsByNewestRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorID,
			&i.AuthorName,
			&i.ReplyCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommentsByOldest = `-- name: ListCommentsByOldest :many
SELECT comments.id, comments.parent_id, comments.content, comments.created_at, comments.updated_at, users.id AS author_id, users.name AS author_name,
    (SELECT COUNT(*) FROM comments AS replies WHERE replies.parent_id = comments.id) AS reply_count
FROM comments
JOIN users ON comments.user_id = users.id
WHERE comments.post_id = $1
AND(
($3::uuid IS NULL AND comments.parent_id IS NULL)
OR
(comments.parent_id = $3)
)
AND ($4::timestamp IS NULL OR comments.created_at > $4)
ORDER BY comments.created_at ASC
LIMIT $2
`

type ListCommentsByOldestParams struct {
	PostID   uuid.UUID        `json:"post_id"`
	Limit    int32            `json:"limit"`
	ParentID pgtype.UUID      `json:"parent_id"`
	Cursor   pgtype.Timestamp `json:"cursor"`
}

type ListCommentsByOldestRow struct {
	ID         uuid.UUID   `json:"id"`
	ParentID   pgtype.UUID `json:"parent_id"`
	Content    string      `json:"content"`
	CreatedAt  time.Time   `json:"created_at"`
	UpdatedAt  time.Time   `json:"updated_at"`
	AuthorID   uuid.UUID   `json:"author_id"`
	AuthorName string      `json:"author_name"`
	ReplyCount int64       `json:"reply_count"`
}

func (q *Queries) ListCommentsByOldest(ctx context.Context, arg ListCommentsByOldestParams) ([]ListCommentsByOldestRow, error) {
	rows, err := q.db.Query(ctx, listCommentsByOldest,
		arg.PostID,
		arg.Limit,
		arg.ParentID,
		arg.Cursor,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentsByOldestRow
	for rows.Next() {
		var i ListCommentsByOldestRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorID,
			&i.AuthorName,
			&i.ReplyCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateComment = `-- name: UpdateComment :one
UPDATE comments
SET content = $3, updated_at = $4
WHERE id = $1 AND user_id = $2
RETURNING id, post_id, user_id, content, created_at, updated_at, parent_id, score
`

type UpdateCommentParams struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Content   string    `json:"content"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, updateComment,
		arg.ID,
		arg.UserID,
		arg.Content,
		arg.UpdatedAt,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentID,
		&i.Score,
	)
	return i, err
}
