// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type PostCategory string

const (
	PostCategoryPENDING        PostCategory = "PENDING"
	PostCategoryINFRASTRUCTURE PostCategory = "INFRASTRUCTURE"
	PostCategoryECONOMY        PostCategory = "ECONOMY"
	PostCategoryHEALTHCARE     PostCategory = "HEALTHCARE"
	PostCategoryEDUCATION      PostCategory = "EDUCATION"
	PostCategoryENVIRONMENT    PostCategory = "ENVIRONMENT"
	PostCategorySAFETY         PostCategory = "SAFETY"
	PostCategoryOTHER          PostCategory = "OTHER"
)

func (e *PostCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PostCategory(s)
	case string:
		*e = PostCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for PostCategory: %T", src)
	}
	return nil
}

type NullPostCategory struct {
	PostCategory PostCategory `json:"post_category"`
	Valid        bool         `json:"valid"` // Valid is true if PostCategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPostCategory) Scan(value interface{}) error {
	if value == nil {
		ns.PostCategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PostCategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPostCategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PostCategory), nil
}

type BackgroundJob struct {
	ID           uuid.UUID   `json:"id"`
	JobType      string      `json:"job_type"`
	Payload      []byte      `json:"payload"`
	Status       string      `json:"status"`
	ErrorMessage pgtype.Text `json:"error_message"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

type CategoryReport struct {
	ID          uuid.UUID    `json:"id"`
	Category    PostCategory `json:"category"`
	Report      []byte       `json:"report"`
	GeneratedAt time.Time    `json:"generated_at"`
}

type Comment struct {
	ID        uuid.UUID   `json:"id"`
	PostID    uuid.UUID   `json:"post_id"`
	UserID    uuid.UUID   `json:"user_id"`
	Content   string      `json:"content"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
	ParentID  pgtype.UUID `json:"parent_id"`
	Score     int32       `json:"score"`
}

type CommentVote struct {
	CommentID uuid.UUID          `json:"comment_id"`
	UserID    uuid.UUID          `json:"user_id"`
	Vote      int16              `json:"vote"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Post struct {
	ID        uuid.UUID    `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	Title     string       `json:"title"`
	Content   string       `json:"content"`
	Category  PostCategory `json:"category"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	Score     int32        `json:"score"`
	Summary   pgtype.Text  `json:"summary"`
}

type PostVote struct {
	PostID    uuid.UUID          `json:"post_id"`
	UserID    uuid.UUID          `json:"user_id"`
	Vote      int16              `json:"vote"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID             uuid.UUID `json:"id"`
	Name           string    `json:"name"`
	Email          string    `json:"email"`
	HashedPassword string    `json:"hashed_password"`
	KycStatus      string    `json:"kyc_status"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}
