// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: posts.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (id, user_id, title, content, category, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, title, content, category, created_at, updated_at
`

type CreatePostParams struct {
	ID        uuid.UUID    `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	Title     string       `json:"title"`
	Content   string       `json:"content"`
	Category  PostCategory `json:"category"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Content,
		arg.Category,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Content,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPostByID = `-- name: GetPostByID :one
SELECT posts.id, posts.title, posts.content, posts.category, posts.created_at, posts.updated_at, users.id AS author_id, users.name AS author_name
FROM posts
JOIN users ON posts.user_id = users.id
WHERE posts.id = $1 LIMIT 1
`

type GetPostByIDRow struct {
	ID         uuid.UUID    `json:"id"`
	Title      string       `json:"title"`
	Content    string       `json:"content"`
	Category   PostCategory `json:"category"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
	AuthorID   uuid.UUID    `json:"author_id"`
	AuthorName string       `json:"author_name"`
}

func (q *Queries) GetPostByID(ctx context.Context, id uuid.UUID) (GetPostByIDRow, error) {
	row := q.db.QueryRow(ctx, getPostByID, id)
	var i GetPostByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorID,
		&i.AuthorName,
	)
	return i, err
}

const listPosts = `-- name: ListPosts :many
SELECT posts.id, posts.title, posts.category, posts.created_at, users.name AS author_name
FROM posts
JOIN users ON posts.user_id = users.id
WHERE ($3::post_category IS NULL OR posts.category = $3)
ORDER BY posts.created_at DESC
LIMIT $1 OFFSET $2
`

type ListPostsParams struct {
	Limit    int32        `json:"limit"`
	Offset   int32        `json:"offset"`
	Category PostCategory `json:"category"`
}

type ListPostsRow struct {
	ID         uuid.UUID    `json:"id"`
	Title      string       `json:"title"`
	Category   PostCategory `json:"category"`
	CreatedAt  time.Time    `json:"created_at"`
	AuthorName string       `json:"author_name"`
}

func (q *Queries) ListPosts(ctx context.Context, arg ListPostsParams) ([]ListPostsRow, error) {
	rows, err := q.db.Query(ctx, listPosts, arg.Limit, arg.Offset, arg.Category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostsRow
	for rows.Next() {
		var i ListPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Category,
			&i.CreatedAt,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
