// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: posts.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const atomicUpdatePostScore = `-- name: AtomicUpdatePostScore :exec
UPDATE posts
SET score = score + $2
WHERE id = $1
`

type AtomicUpdatePostScoreParams struct {
	ID    uuid.UUID `json:"id"`
	Score int32     `json:"score"`
}

// Let the database engine to do the math to guarantee absolute precision
func (q *Queries) AtomicUpdatePostScore(ctx context.Context, arg AtomicUpdatePostScoreParams) error {
	_, err := q.db.Exec(ctx, atomicUpdatePostScore, arg.ID, arg.Score)
	return err
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (id, user_id, title, content, category, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, title, content, category, created_at, updated_at, score, summary
`

type CreatePostParams struct {
	ID        uuid.UUID    `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	Title     string       `json:"title"`
	Content   string       `json:"content"`
	Category  PostCategory `json:"category"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Content,
		arg.Category,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Content,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Score,
		&i.Summary,
	)
	return i, err
}

const deletePost = `-- name: DeletePost :execrows
DELETE FROM posts
WHERE id = $1 AND user_id = $2
`

type DeletePostParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeletePost(ctx context.Context, arg DeletePostParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePost, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPostByID = `-- name: GetPostByID :one
SELECT posts.id, posts.title, posts.content, posts.category, posts.created_at, posts.updated_at, posts.score, posts.summary,
    users.id AS author_id, users.name AS author_name,
    COALESCE(pv.vote,0)::smallint AS user_vote
FROM posts
JOIN users ON posts.user_id = users.id
LEFT JOIN post_votes pv ON pv.post_id = posts.id AND pv.user_id = $2::uuid
WHERE posts.id = $1 LIMIT 1
`

type GetPostByIDParams struct {
	ID            uuid.UUID   `json:"id"`
	CurrentUserID pgtype.UUID `json:"current_user_id"`
}

type GetPostByIDRow struct {
	ID         uuid.UUID    `json:"id"`
	Title      string       `json:"title"`
	Content    string       `json:"content"`
	Category   PostCategory `json:"category"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
	Score      int32        `json:"score"`
	Summary    pgtype.Text  `json:"summary"`
	AuthorID   uuid.UUID    `json:"author_id"`
	AuthorName string       `json:"author_name"`
	UserVote   int16        `json:"user_vote"`
}

func (q *Queries) GetPostByID(ctx context.Context, arg GetPostByIDParams) (GetPostByIDRow, error) {
	row := q.db.QueryRow(ctx, getPostByID, arg.ID, arg.CurrentUserID)
	var i GetPostByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Score,
		&i.Summary,
		&i.AuthorID,
		&i.AuthorName,
		&i.UserVote,
	)
	return i, err
}

const getPostVoteForUpdate = `-- name: GetPostVoteForUpdate :one
SELECT vote from post_votes WHERE post_id = $1 AND user_id = $2
FOR UPDATE
`

type GetPostVoteForUpdateParams struct {
	PostID uuid.UUID `json:"post_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetPostVoteForUpdate(ctx context.Context, arg GetPostVoteForUpdateParams) (int16, error) {
	row := q.db.QueryRow(ctx, getPostVoteForUpdate, arg.PostID, arg.UserID)
	var vote int16
	err := row.Scan(&vote)
	return vote, err
}

const getTopPostsWithComments = `-- name: GetTopPostsWithComments :many
WITH recent_posts AS (
    SELECT id,title,content,score,created_at
    FROM posts
    WHERE category = $1
    ORDER BY created_at DESC
    LIMIT 5
)
SELECT rp.id,rp.title,rp.content,rp.score,rp.created_at,
    COALESCE(
        (
            SELECT json_agg(
                json_build_object(
                    'id', c.id,
                    'content', c.content,
                    'score', c.score,
                    'created_at', c.created_at
                )
            )
            FROM(
                SELECT id,content,score,created_at
                FROM comments
                WHERE post_id = rp.id
                ORDER BY score DESC
                LIMIT 5
            ) c
        ),
        '[]'::json
    )::json AS top_comments
FROM recent_posts rp
ORDER BY rp.created_at DESC
`

type GetTopPostsWithCommentsRow struct {
	ID          uuid.UUID `json:"id"`
	Title       string    `json:"title"`
	Content     string    `json:"content"`
	Score       int32     `json:"score"`
	CreatedAt   time.Time `json:"created_at"`
	TopComments []byte    `json:"top_comments"`
}

func (q *Queries) GetTopPostsWithComments(ctx context.Context, category PostCategory) ([]GetTopPostsWithCommentsRow, error) {
	rows, err := q.db.Query(ctx, getTopPostsWithComments, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopPostsWithCommentsRow
	for rows.Next() {
		var i GetTopPostsWithCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.Score,
			&i.CreatedAt,
			&i.TopComments,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPostVote = `-- name: InsertPostVote :exec
INSERT INTO post_votes (post_id, user_id, vote)
VALUES ($1, $2, $3)
`

type InsertPostVoteParams struct {
	PostID uuid.UUID `json:"post_id"`
	UserID uuid.UUID `json:"user_id"`
	Vote   int16     `json:"vote"`
}

// STRICT INSERT. If two threads try to insert at the same time, will get unique violation error
func (q *Queries) InsertPostVote(ctx context.Context, arg InsertPostVoteParams) error {
	_, err := q.db.Exec(ctx, insertPostVote, arg.PostID, arg.UserID, arg.Vote)
	return err
}

const listPostsByNewest = `-- name: ListPostsByNewest :many
SELECT posts.id, posts.title, posts.category, posts.created_at, posts.updated_at, posts.score,
    users.name AS author_name, users.id AS author_id,
    COALESCE(pv.vote,0)::smallint AS user_vote
FROM posts
JOIN users ON posts.user_id = users.id
LEFT JOIN post_votes pv ON pv.post_id = posts.id AND pv.user_id = $2::uuid
WHERE ($3::post_category IS NULL OR posts.category = $3)
AND ($4::timestamp IS NULL OR posts.created_at < $4)
ORDER BY posts.created_at DESC
LIMIT $1
`

type ListPostsByNewestParams struct {
	Limit         int32            `json:"limit"`
	CurrentUserID pgtype.UUID      `json:"current_user_id"`
	Category      NullPostCategory `json:"category"`
	Cursor        pgtype.Timestamp `json:"cursor"`
}

type ListPostsByNewestRow struct {
	ID         uuid.UUID    `json:"id"`
	Title      string       `json:"title"`
	Category   PostCategory `json:"category"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
	Score      int32        `json:"score"`
	AuthorName string       `json:"author_name"`
	AuthorID   uuid.UUID    `json:"author_id"`
	UserVote   int16        `json:"user_vote"`
}

func (q *Queries) ListPostsByNewest(ctx context.Context, arg ListPostsByNewestParams) ([]ListPostsByNewestRow, error) {
	rows, err := q.db.Query(ctx, listPostsByNewest,
		arg.Limit,
		arg.CurrentUserID,
		arg.Category,
		arg.Cursor,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostsByNewestRow
	for rows.Next() {
		var i ListPostsByNewestRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Category,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Score,
			&i.AuthorName,
			&i.AuthorID,
			&i.UserVote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsByOldest = `-- name: ListPostsByOldest :many
SELECT posts.id, posts.title, posts.category, posts.created_at, posts.updated_at, posts.score,
    users.name AS author_name, users.id AS author_id,
    COALESCE(pv.vote,0)::smallint AS user_vote
FROM posts
JOIN users ON posts.user_id = users.id
LEFT JOIN post_votes pv ON pv.post_id = posts.id AND pv.user_id = $2::uuid
WHERE ($3::post_category IS NULL OR posts.category = $3)
AND ($4::timestamp IS NULL OR posts.created_at > $4)
ORDER BY posts.created_at ASC
LIMIT $1
`

type ListPostsByOldestParams struct {
	Limit         int32            `json:"limit"`
	CurrentUserID pgtype.UUID      `json:"current_user_id"`
	Category      NullPostCategory `json:"category"`
	Cursor        pgtype.Timestamp `json:"cursor"`
}

type ListPostsByOldestRow struct {
	ID         uuid.UUID    `json:"id"`
	Title      string       `json:"title"`
	Category   PostCategory `json:"category"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
	Score      int32        `json:"score"`
	AuthorName string       `json:"author_name"`
	AuthorID   uuid.UUID    `json:"author_id"`
	UserVote   int16        `json:"user_vote"`
}

func (q *Queries) ListPostsByOldest(ctx context.Context, arg ListPostsByOldestParams) ([]ListPostsByOldestRow, error) {
	rows, err := q.db.Query(ctx, listPostsByOldest,
		arg.Limit,
		arg.CurrentUserID,
		arg.Category,
		arg.Cursor,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostsByOldestRow
	for rows.Next() {
		var i ListPostsByOldestRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Category,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Score,
			&i.AuthorName,
			&i.AuthorID,
			&i.UserVote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsByPopular = `-- name: ListPostsByPopular :many
SELECT posts.id, posts.title, posts.category, posts.created_at, posts.updated_at, posts.score,
    users.name AS author_name, users.id AS author_id,
    COALESCE(pv.vote,0)::smallint AS user_vote
FROM posts
JOIN users ON posts.user_id = users.id
LEFT JOIN post_votes pv ON pv.post_id = posts.id AND pv.user_id = $3::uuid
WHERE ($4::post_category IS NULL OR posts.category = $4)
ORDER BY posts.score DESC, posts.created_at DESC
LIMIT $1 OFFSET $2
`

type ListPostsByPopularParams struct {
	Limit         int32            `json:"limit"`
	Offset        int32            `json:"offset"`
	CurrentUserID pgtype.UUID      `json:"current_user_id"`
	Category      NullPostCategory `json:"category"`
}

type ListPostsByPopularRow struct {
	ID         uuid.UUID    `json:"id"`
	Title      string       `json:"title"`
	Category   PostCategory `json:"category"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
	Score      int32        `json:"score"`
	AuthorName string       `json:"author_name"`
	AuthorID   uuid.UUID    `json:"author_id"`
	UserVote   int16        `json:"user_vote"`
}

func (q *Queries) ListPostsByPopular(ctx context.Context, arg ListPostsByPopularParams) ([]ListPostsByPopularRow, error) {
	rows, err := q.db.Query(ctx, listPostsByPopular,
		arg.Limit,
		arg.Offset,
		arg.CurrentUserID,
		arg.Category,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostsByPopularRow
	for rows.Next() {
		var i ListPostsByPopularRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Category,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Score,
			&i.AuthorName,
			&i.AuthorID,
			&i.UserVote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsByUser = `-- name: ListPostsByUser :many
SELECT posts.id, posts.title, posts.content, posts.category, posts.created_at, posts.updated_at, posts.score,
    users.name AS author_name, users.id AS author_id,
    COALESCE(pv.vote,0)::smallint AS user_vote
FROM posts
JOIN users ON posts.user_id = users.id
LEFT JOIN post_votes pv ON pv.post_id = posts.id AND pv.user_id = $3::uuid
WHERE posts.user_id = $1
AND ($4::timestamp IS NULL OR posts.created_at < $4)
ORDER BY posts.created_at DESC
LIMIT $2
`

type ListPostsByUserParams struct {
	UserID        uuid.UUID        `json:"user_id"`
	Limit         int32            `json:"limit"`
	CurrentUserID pgtype.UUID      `json:"current_user_id"`
	Cursor        pgtype.Timestamp `json:"cursor"`
}

type ListPostsByUserRow struct {
	ID         uuid.UUID    `json:"id"`
	Title      string       `json:"title"`
	Content    string       `json:"content"`
	Category   PostCategory `json:"category"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
	Score      int32        `json:"score"`
	AuthorName string       `json:"author_name"`
	AuthorID   uuid.UUID    `json:"author_id"`
	UserVote   int16        `json:"user_vote"`
}

func (q *Queries) ListPostsByUser(ctx context.Context, arg ListPostsByUserParams) ([]ListPostsByUserRow, error) {
	rows, err := q.db.Query(ctx, listPostsByUser,
		arg.UserID,
		arg.Limit,
		arg.CurrentUserID,
		arg.Cursor,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostsByUserRow
	for rows.Next() {
		var i ListPostsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.Category,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Score,
			&i.AuthorName,
			&i.AuthorID,
			&i.UserVote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpvotedPostsByUser = `-- name: ListUpvotedPostsByUser :many
SELECT posts.id, posts.title, posts.content, posts.category, posts.created_at, posts.updated_at, posts.score,
    users.name AS author_name, users.id AS author_id,
    1::smallint AS user_vote -- We hardcode 1 because they must have upvoted it to be in this list!
FROM posts
JOIN users ON posts.user_id = users.id
JOIN post_votes pv ON pv.post_id = posts.id
WHERE pv.user_id = $1 AND pv.vote = 1
AND ($3::timestamp IS NULL OR posts.created_at < $3)
ORDER BY posts.created_at DESC
LIMIT $2
`

type ListUpvotedPostsByUserParams struct {
	UserID uuid.UUID        `json:"user_id"`
	Limit  int32            `json:"limit"`
	Cursor pgtype.Timestamp `json:"cursor"`
}

type ListUpvotedPostsByUserRow struct {
	ID         uuid.UUID    `json:"id"`
	Title      string       `json:"title"`
	Content    string       `json:"content"`
	Category   PostCategory `json:"category"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
	Score      int32        `json:"score"`
	AuthorName string       `json:"author_name"`
	AuthorID   uuid.UUID    `json:"author_id"`
	UserVote   int16        `json:"user_vote"`
}

func (q *Queries) ListUpvotedPostsByUser(ctx context.Context, arg ListUpvotedPostsByUserParams) ([]ListUpvotedPostsByUserRow, error) {
	rows, err := q.db.Query(ctx, listUpvotedPostsByUser, arg.UserID, arg.Limit, arg.Cursor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUpvotedPostsByUserRow
	for rows.Next() {
		var i ListUpvotedPostsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.Category,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Score,
			&i.AuthorName,
			&i.AuthorID,
			&i.UserVote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removePostVote = `-- name: RemovePostVote :exec
DELETE FROM post_votes WHERE post_id = $1 AND user_id = $2
`

type RemovePostVoteParams struct {
	PostID uuid.UUID `json:"post_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RemovePostVote(ctx context.Context, arg RemovePostVoteParams) error {
	_, err := q.db.Exec(ctx, removePostVote, arg.PostID, arg.UserID)
	return err
}

const updatePost = `-- name: UpdatePost :one
UPDATE posts
SET title = $3, content = $4, category = $5, updated_at = $6
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, title, content, category, created_at, updated_at, score, summary
`

type UpdatePostParams struct {
	ID        uuid.UUID    `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	Title     string       `json:"title"`
	Content   string       `json:"content"`
	Category  PostCategory `json:"category"`
	UpdatedAt time.Time    `json:"updated_at"`
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, updatePost,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Content,
		arg.Category,
		arg.UpdatedAt,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Content,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Score,
		&i.Summary,
	)
	return i, err
}

const updatePostCategory = `-- name: UpdatePostCategory :exec
UPDATE posts
SET category = $2, updated_at = $3
WHERE id = $1
`

type UpdatePostCategoryParams struct {
	ID        uuid.UUID    `json:"id"`
	Category  PostCategory `json:"category"`
	UpdatedAt time.Time    `json:"updated_at"`
}

func (q *Queries) UpdatePostCategory(ctx context.Context, arg UpdatePostCategoryParams) error {
	_, err := q.db.Exec(ctx, updatePostCategory, arg.ID, arg.Category, arg.UpdatedAt)
	return err
}

const updatePostVote = `-- name: UpdatePostVote :exec
UPDATE post_votes SET vote = $3
WHERE post_id = $1 AND user_id = $2
`

type UpdatePostVoteParams struct {
	PostID uuid.UUID `json:"post_id"`
	UserID uuid.UUID `json:"user_id"`
	Vote   int16     `json:"vote"`
}

func (q *Queries) UpdatePostVote(ctx context.Context, arg UpdatePostVoteParams) error {
	_, err := q.db.Exec(ctx, updatePostVote, arg.PostID, arg.UserID, arg.Vote)
	return err
}
