// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkSummaryJobStatus = `-- name: CheckSummaryJobStatus :one
SELECT status, created_at
FROM background_jobs
WHERE job_type = 'EXEC_SUMMARY'
AND payload->>'post_id' = $1::text
ORDER BY created_at DESC
LIMIT 1
`

type CheckSummaryJobStatusRow struct {
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
}

// used by the SSE endpoint to check if frontend need update UI
func (q *Queries) CheckSummaryJobStatus(ctx context.Context, dollar_1 string) (CheckSummaryJobStatusRow, error) {
	row := q.db.QueryRow(ctx, checkSummaryJobStatus, dollar_1)
	var i CheckSummaryJobStatusRow
	err := row.Scan(&i.Status, &i.CreatedAt)
	return i, err
}

const completeJob = `-- name: CompleteJob :exec
UPDATE background_jobs
SET status = 'COMPLETED', updated_at = $2
WHERE id = $1
`

type CompleteJobParams struct {
	ID        uuid.UUID `json:"id"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) CompleteJob(ctx context.Context, arg CompleteJobParams) error {
	_, err := q.db.Exec(ctx, completeJob, arg.ID, arg.UpdatedAt)
	return err
}

const dequeueJob = `-- name: DequeueJob :one
UPDATE background_jobs
SET status = 'PROCESSING', updated_at = $1
WHERE id = (
    SELECT id
    FROM background_jobs
    WHERE status = 'PENDING'
    ORDER BY created_at ASC
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING id, job_type, payload
`

type DequeueJobRow struct {
	ID      uuid.UUID `json:"id"`
	JobType string    `json:"job_type"`
	Payload []byte    `json:"payload"`
}

// Finds the oldest PENDING job, locks it, mark it PROCESSING, and hands it to the Go Worker
func (q *Queries) DequeueJob(ctx context.Context, updatedAt time.Time) (DequeueJobRow, error) {
	row := q.db.QueryRow(ctx, dequeueJob, updatedAt)
	var i DequeueJobRow
	err := row.Scan(&i.ID, &i.JobType, &i.Payload)
	return i, err
}

const enqueueJob = `-- name: EnqueueJob :exec
INSERT INTO background_jobs (id, job_type, payload, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type EnqueueJobParams struct {
	ID        uuid.UUID `json:"id"`
	JobType   string    `json:"job_type"`
	Payload   []byte    `json:"payload"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) EnqueueJob(ctx context.Context, arg EnqueueJobParams) error {
	_, err := q.db.Exec(ctx, enqueueJob,
		arg.ID,
		arg.JobType,
		arg.Payload,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const failJob = `-- name: FailJob :exec
UPDATE background_jobs
SET status = 'FAILED', error_message = $2, updated_at = $3
WHERE id = $1
`

type FailJobParams struct {
	ID           uuid.UUID   `json:"id"`
	ErrorMessage pgtype.Text `json:"error_message"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

func (q *Queries) FailJob(ctx context.Context, arg FailJobParams) error {
	_, err := q.db.Exec(ctx, failJob, arg.ID, arg.ErrorMessage, arg.UpdatedAt)
	return err
}

const getPostForWorker = `-- name: GetPostForWorker :one
SELECT id, title, content
FROM posts
WHERE id = $1 LIMIT 1
`

type GetPostForWorkerRow struct {
	ID      uuid.UUID `json:"id"`
	Title   string    `json:"title"`
	Content string    `json:"content"`
}

// query for background jobs, no joins
func (q *Queries) GetPostForWorker(ctx context.Context, id uuid.UUID) (GetPostForWorkerRow, error) {
	row := q.db.QueryRow(ctx, getPostForWorker, id)
	var i GetPostForWorkerRow
	err := row.Scan(&i.ID, &i.Title, &i.Content)
	return i, err
}

const updatePostSummary = `-- name: UpdatePostSummary :exec
UPDATE posts
SET summary = $2, updated_at = $3
WHERE id = $1
`

type UpdatePostSummaryParams struct {
	ID        uuid.UUID   `json:"id"`
	Summary   pgtype.Text `json:"summary"`
	UpdatedAt time.Time   `json:"updated_at"`
}

// save the finished summary back to the posts
func (q *Queries) UpdatePostSummary(ctx context.Context, arg UpdatePostSummaryParams) error {
	_, err := q.db.Exec(ctx, updatePostSummary, arg.ID, arg.Summary, arg.UpdatedAt)
	return err
}
