// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Let the database engine to do the math to guarantee absolute precision
	AtomicUpdatePostScore(ctx context.Context, arg AtomicUpdatePostScoreParams) error
	CreateComments(ctx context.Context, arg CreateCommentsParams) (Comment, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteComment(ctx context.Context, arg DeleteCommentParams) (int64, error)
	DeletePost(ctx context.Context, arg DeletePostParams) (int64, error)
	GetCommentVote(ctx context.Context, arg GetCommentVoteParams) (int16, error)
	GetPostByID(ctx context.Context, arg GetPostByIDParams) (GetPostByIDRow, error)
	GetPostVoteForUpdate(ctx context.Context, arg GetPostVoteForUpdateParams) (int16, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error)
	GlobalSearch(ctx context.Context, searchQuery string) ([]GlobalSearchRow, error)
	// STRICT INSERT. If two threads try to insert at the same time, will get unique violation error
	InsertPostVote(ctx context.Context, arg InsertPostVoteParams) error
	ListCommentsByNewest(ctx context.Context, arg ListCommentsByNewestParams) ([]ListCommentsByNewestRow, error)
	ListCommentsByOldest(ctx context.Context, arg ListCommentsByOldestParams) ([]ListCommentsByOldestRow, error)
	ListCommentsByPopular(ctx context.Context, arg ListCommentsByPopularParams) ([]ListCommentsByPopularRow, error)
	ListCommentsByUser(ctx context.Context, arg ListCommentsByUserParams) ([]ListCommentsByUserRow, error)
	ListPostsByNewest(ctx context.Context, arg ListPostsByNewestParams) ([]ListPostsByNewestRow, error)
	ListPostsByOldest(ctx context.Context, arg ListPostsByOldestParams) ([]ListPostsByOldestRow, error)
	ListPostsByPopular(ctx context.Context, arg ListPostsByPopularParams) ([]ListPostsByPopularRow, error)
	ListPostsByUser(ctx context.Context, arg ListPostsByUserParams) ([]ListPostsByUserRow, error)
	ListUpvotedCommentsByUser(ctx context.Context, arg ListUpvotedCommentsByUserParams) ([]ListUpvotedCommentsByUserRow, error)
	ListUpvotedPostsByUser(ctx context.Context, arg ListUpvotedPostsByUserParams) ([]ListUpvotedPostsByUserRow, error)
	RemoveCommentVote(ctx context.Context, arg RemoveCommentVoteParams) error
	RemovePostVote(ctx context.Context, arg RemovePostVoteParams) error
	SetCommentVote(ctx context.Context, arg SetCommentVoteParams) error
	UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error)
	UpdateCommentScore(ctx context.Context, arg UpdateCommentScoreParams) error
	UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error)
	UpdatePostCategory(ctx context.Context, arg UpdatePostCategoryParams) error
	UpdatePostVote(ctx context.Context, arg UpdatePostVoteParams) error
}

var _ Querier = (*Queries)(nil)
