// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getLatestCategoryReport = `-- name: GetLatestCategoryReport :one
SELECT id, category, report, generated_at
FROM category_reports
WHERE category = $1
ORDER BY generated_at DESC
LIMIT 1
`

func (q *Queries) GetLatestCategoryReport(ctx context.Context, category PostCategory) (CategoryReport, error) {
	row := q.db.QueryRow(ctx, getLatestCategoryReport, category)
	var i CategoryReport
	err := row.Scan(
		&i.ID,
		&i.Category,
		&i.Report,
		&i.GeneratedAt,
	)
	return i, err
}

const saveCategoryReport = `-- name: SaveCategoryReport :exec
INSERT INTO category_reports (id, category, report, generated_at)
VALUES ($1, $2, $3, $4)
`

type SaveCategoryReportParams struct {
	ID          uuid.UUID    `json:"id"`
	Category    PostCategory `json:"category"`
	Report      []byte       `json:"report"`
	GeneratedAt time.Time    `json:"generated_at"`
}

func (q *Queries) SaveCategoryReport(ctx context.Context, arg SaveCategoryReportParams) error {
	_, err := q.db.Exec(ctx, saveCategoryReport,
		arg.ID,
		arg.Category,
		arg.Report,
		arg.GeneratedAt,
	)
	return err
}
