// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: search.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const globalSearch = `-- name: GlobalSearch :many
SELECT 'post'::text AS result_type, p.id AS unique_id, p.id as url_id, p.title, p.content, p.category, u.name AS author_name, p.created_at
FROM posts p
JOIN users u ON p.user_id = u.id
WHERE to_tsvector('english', p.title || ' ' || p.content || ' ' || p.category) @@ plainto_tsquery('english', $1::text)

UNION ALL

SELECT 'comment'::text AS result_type, c.id as unique_id, c.post_id AS url_id, p.title AS title, c.content, p.category AS category, u.name AS author_name, c.created_at
FROM comments c
JOIN users u ON c.user_id = u.id
JOIN posts p ON c.post_id = p.id
WHERE to_tsvector('english', c.content || ' ' || p.category) @@ plainto_tsquery('english', $1::text)

ORDER BY created_at DESC
Limit 20
`

type GlobalSearchRow struct {
	ResultType string       `json:"result_type"`
	UniqueID   uuid.UUID    `json:"unique_id"`
	UrlID      uuid.UUID    `json:"url_id"`
	Title      string       `json:"title"`
	Content    string       `json:"content"`
	Category   PostCategory `json:"category"`
	AuthorName string       `json:"author_name"`
	CreatedAt  time.Time    `json:"created_at"`
}

func (q *Queries) GlobalSearch(ctx context.Context, searchQuery string) ([]GlobalSearchRow, error) {
	rows, err := q.db.Query(ctx, globalSearch, searchQuery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GlobalSearchRow
	for rows.Next() {
		var i GlobalSearchRow
		if err := rows.Scan(
			&i.ResultType,
			&i.UniqueID,
			&i.UrlID,
			&i.Title,
			&i.Content,
			&i.Category,
			&i.AuthorName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
